name: StayPut
version: 1.2
api-version: 1.13
author: Zander van der Meer
main: nl.zandervdm.stayput.Main
website: http://zandervdm.nl
depend: [Multiverse-Core]
commands:
    stayput:
        description: Main command
        usage: /stayput <command>
        aliases: [stay, sp]